### ISSUE TITLE
How to get started

### ISSUE THREAD

**Issue by BastiJoe** [point85/OEE-Designer#1]
Hi Kent,

I'm absolutely new to programming, but I would like to check out your oee tool.
I downloaded the package and tried to run "run-tester-app.bat", but I get the error "javaw.exe was not found". 
Sorry for that stupid question, but I couldn't find a solution on the internet.

Thank you so far.

Best regards,

Sebastian

**Comment by point85** [comment]
Please follow the instructions in the Getting Started guide. In this case there needs to be a Java 8 32 bit JRE on your class path

**Comment by point85** [comment]
Set JAVA_HOME = path to JRE

**Comment by BastiJoe** [comment]
Thank you so far. I managed to get the "Starting Application. Please wait..." window, but then it just closes.
I will spend some time to try to find out how it works. 
Best regards,
Sebastian

**Comment by point85** [comment]
I am guessing that you were unable to connect to your database.  Look for a file called Point85.log in the /logs folder. It will have more information

**Comment by BastiJoe** [comment]
It says

2019-02-11 19:30:05.560 INFO  OeeApplication - Initializing persistence service with args: jdbc:sqlserver://localhost:1433;databaseName=OEE, Point85, Point85
2019-02-11 19:30:35.613 ERROR PersistenceService - Unable to create an EntityManagerFactory after 30 seconds.

**Comment by point85** [comment]
This is the default JDBC connection string for SQL server with a Point85 user in the OEE database. You can install a database and create your own user. BTW please use my latest release 2.0.0 which supports 4 databases

**Comment by tsulatsitamim** [comment]
thanks for this great software.

i try to open app in ubuntu but I get 
`Error: Could not find or load main class org.point85.app.OeeApplication
`
how to properly open in in linux (ubuntu)

**Comment by point85** [comment]
Are you using the Open JRE for Java 8?  I have only tested on the Oracle
Java 8 distribution for Linux 64.  I believe Open JRE class loader must be
using the classpath differently than in the .sh scripts I have provided for
the Oracle JRE.
