### ISSUE TITLE
Java paths with spaces won't work on Windows (*.bat files)

### ISSUE THREAD

**Issue by gregid** [point85/OEE-Designer#15]
None of the *.bat files will work if the %JAVA_HOME% and %JAVAFX_HOME% paths include spaces on Windows (e.g. most common `C:\Program Files\JAVAHOME\`)

The error will be  `System Windows cannot find C:\Program`

 - OS: Win 10
 - Version 3.7.0, 3.8.0

These paths should be wrapped in double quotes.

**Comment by point85** [comment]
The cleanest generic option is to use the system environment variable JAVA_HOME pointing to the bin folder.  Then in the batch files just "start javaw.exe".  If you have another location, just put the full path in the .bat files.

**Comment by gregid** [comment]
In case you would decide to change `*.bat` files to also work with more problematic paths here is where the double quotes should be:
```
start "" "%JAVA_HOME%bin\javaw.exe" -p "%JAVAFX_HOME%\lib" --add-modules javafx.controls,javafx.fxml,javafx.web -Dlog4j.configurationFile=config\logging\log4j2.xml -jar oee-apps-3.7.0.jar DESIGNER jdbc:hsqldb:hsql://localhost/OEE SA 
```
The empty `""` is required for cmd window title when double quotes are used.

**Comment by gregid** [comment]
With the changes in commit:
https://github.com/point85/OEE-Designer/commit/d905065cbd3bc71084b47effc9e5b967616152a9

It would still fail if `%JAVAFX_HOME%` contain spaces

**Comment by point85** [comment]
Thanks gregid.  I updated the Wiindows batch files accordingly
