### ISSUE TITLE
Monitor application sample data

### ISSUE THREAD

**Issue by vraghu1983** [point85/OEE-Designer#2]
Hi - I went through the samples, and would like to know how the monitor application can be envisioned with some sample static data. So, any samples in this regard will be useful. 
Thank you in advance.

**Comment by point85** [comment]
The easiest way to create static data is to use the Monitor's editors to
create events.  Create a material setup first followed by the availability
and production events.  The web operator application can also be deployed
to a web server.  The war file is at
https://github.com/point85/OEE-Operations/releases.

**Comment by une18** [comment]
I studied the documentation of the project. Plan is to use MQTT for data transfer. 
For testing I plan to use Arduino NodeMCU board with photoelectric switch connected to it. 
I got confused what is the exact data that should be sent out?
If 1 product is counted with the sensor, should it send out just "1" or "date,time,1" 
Should it send every counted product as separate data transfer or should it collect and send out 10 product counts with 1 transfer or 1 transfer per minute or...? Maybe You could add into the user manual a sample of the data transfered. 

I need to start with the software, but need some help locally to get all up and running.

**Comment by vraghu1983** [comment]
Thanks. We don't have a setup in the factory as yet but would like to see
how this works so was asking for the simulation of static data. Will give a
try with the material setup and let you know.

**Comment by point85** [comment]
There is one MQTT message per availability, production or setup event.  So
the amount is '1' with an associated unit of measure as defined in the
physical plant model for that equipment.  If you don't have a material
setup event for this equipment, you can use the Monitor's editor to create
one.  The body of the MQTT message is a JSON-serialized
EquipmentEventMessage object.  You can look at that class to see its
attributes.  The ISO 8601 event time string can be sent in the message
itself, set the JavaScript event resolver or left null in which case the
event time is the data collector's current time.

I will add an example EquipmentEventMessage JSON body to the user guide.

**Comment by point85** [comment]
I updated the Point 85 OEE User Guide with an example of a JSON MQTT message.
