### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by cemcap** [point85/OEE-Designer#4]
Hi Mr. Randall,

first of all, thank you for sharing your expertise!

As i was inspecting your code, i realized that internationalization has not yet been scheduled in the current versions. Are there any future plans to support localization?

Kind regards and keep up the good work...

**Comment by point85** [comment]
Yes, the next release will add a JavaFX desktop version of the operator application.  This application will be localizable using resource bundles.  Localization of the other apps depends on user demand.  Which application would you like to see localized?

**Comment by cemcap** [comment]
Well, sorted by order of importance, these would be:

1. Operator,
2. Monitor/Dashboard,
3. Collector and
4. Designer

**Comment by point85** [comment]
All applications with externally visible text have been localized with resource bundles.  Logging output and toString() method are not localized.  Please see the user guide on how to translate the resource bundles.  I would appreciate any translated bundles that can be submitted to Git.
