### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by une18** [point85/OEE-Designer#6]
Hello Kent!

I would like to give it a try. Have no experience with software development or Java.

As I was not sure what to install, I have installed JDK-13.0.1, JRE 8.0_231, Microsoft SQL Server 2012
Have set **Variable Name:** JAVA_HOME and **Variable Value:** C:\Program Files\Java\jdk-13.0.1

Started the file run_hsqldb_server, and it closed itself.

I get stuck In the next part below. I have downloaded and extracted the archives. Should I rename the folders? Can You show a folder tree, or... I am a bit confused.

_Download the oee.zip file and expand the archive
into the following folder structure:
root: oee-apps-<version>.jar (Designer, Monitor, Collector, Operator and Tester apps), oee-collector-<version>.jar (data collector in-process app), run-collector-app.bat (example Windows shellscript for executing the data collector test UI), run-designer-app.bat (example Windows shell scriptfor executing the designer application), run-monitor-app.bat (example Windows shell script for executing the monitor app), run-tester-app.bat (example Windows shell script for executing the testerapplication) and run-operator-app.bat (example Windows shell script for executing the operator application) ._

**Comment by point85** [comment]
My recommendation is to follow each step in the Getting Started Guide

**Comment by une18** [comment]
I follow the steps, but don´t understand the exact meaning of "expand achive". Is it the same as extract? When I googled, I understood, that I should just rename the file OEE-Designer-master.zip into OEE-Designer-master.jar. Expand archive = Rename file? I used some online file converter to convert zip to jar in case renaming could mess up something.

root: oee-apps-<version>.jar (Designer, Monitor, Collector, Operator and Tester apps)

Sorry, I don´t get. What exactly contains oee-apps-(what is the version?).jar and how to create this file? I understand that designer-master-oee.zip contains all the *.bat and files, but it contains a lot more. For every *.bat file there is a *.sh file...
![image](https://user-images.githubusercontent.com/36228588/69316297-33d18c80-0c41-11ea-9a9f-cbd3275c64b1.png)

**Comment by point85** [comment]
Expand archive means to unzip the zip file.  There are many programs
available to do this such as 7-Zip, WinZip or PkZip.  While I appreciate
your interest in my work, I am not in a position to teach you the basics of
java development or how to run .bat files on Windows or .sh shell files on
Unix.

**Comment by une18** [comment]
Hi Kent!
I am sorry for the trouble caused! As much I have seen in the documentation, You have done a ton of work with the program.

My overall computer knowledge and skill level is above average, but had no contact with java or programming before. The word expand confused me, as I only heared about extract before, i thoght it is connected with Java developement.

I am following your project for more than one year now. A friend was ready to help me with the set-up 6 months ago, but said then NO. I then decided to wait for an "easy to install" version, but feel I can not wait more 😄, so thought i will try myself.

Will it be in an setup.exe phase soon? 

I am working as a production manager in a confectionary factory. I have been looking for a OEE solution, as I have been working with OEE for 10 years in the past, and it has been one of the main kpi-s, but in the current company I can not afford a ready solution. We have 11 positions to measure and some operate only 2 days per month.... 

Some recent contact with home automation and MQTT gave me confedence to try, but I need some help locally here....

Thank You for Your time!

**Comment by point85** [comment]
I would like to take this conversation off of Github.  Please send me your personnal or company email address to point85.llc@gmail.com and I will reply with some steps that you can take.  Once you are past the setup phase, the most important consideration is the data source(s) and how to write the java script to give the reasons and production counts if they are automated.  Otherwise the desktop or web app can be used to manually enter the data.
