### ISSUE TITLE
Install Help

### ISSUE THREAD

**Issue by gwizwald** [point85/OEE-Designer#7]
Having problems installing missing files including .jar files

**Comment by point85** [comment]
What are the errors that you are receiving?  Can you send me screen shots?

**Comment by gwizwald** [comment]
[image: image.png]
[image: image.png]



The step I am on in the getting started guide
[image: image.png]

**Comment by gwizwald** [comment]
[image: image.png]

when I run build all

**Comment by gwizwald** [comment]
When I run from the oee folder location


[image: image.png]

**Comment by point85** [comment]
The images that you attached are not visible in this email.  Please try sending them directly to point85.llc@gmail.com.

**Comment by gwizwald** [comment]
Install directory was wrong, everything working now

**Comment by point85** [comment]
Good to hear that you have the apps running now!
