### ISSUE TITLE
how to run?

### ISSUE THREAD

**Issue by sangjiexun** [point85/OEE-Designer#8]
`mysql:`
![image](https://user-images.githubusercontent.com/59449516/134451086-31555a58-41fa-46fc-ae2a-b2ae881c45dc.png)

`ide:`
![image](https://user-images.githubusercontent.com/59449516/134451066-4e00d028-bb50-46b7-b69e-e330cb22c55c.png)

`run then failure:`
![image](https://user-images.githubusercontent.com/59449516/134451049-c47edd09-d1d9-45ea-87de-b6f7006bffaa.png)

**Comment by sangjiexun** [comment]
![image](https://user-images.githubusercontent.com/59449516/134453131-900b2e4d-f12d-47c1-808b-7bdc2e13d044.png)
and why use this kind runtime?

**Comment by point85** [comment]
Hello CodeJason,
From the screen shot it looks like you are trying to run the Tester GUI
application in an IDE?  First, make sure that you have a 64-bit JVM Java 8+
installed with JavaFX.  Without JavaFX, the application will not run.  The
OpenJDK/JFX versions work fine.

Second, to obtain a detailed log for more information about your execution,
in the config/logging/log4j.properties file change the following to "trace"
from "warn" or "info"
# Hibernate specific
# basic log level for all Hibernate messages:
log4j.logger.org.hibernate=warn

# runtime SQL statements and parameters:
log4j.logger.org.hibernate.SQL=warn

# Log JDBC bind parameter runtime arguments:
log4j.logger.org.hibernate.type=warn

# Hikari database connection pool
log4j.logger.com.zaxxer=warn

# Point85 OEE
log4j.logger.org.point85=info

And, finally, the Tanuki Service Wrapper enables the headless Collector
application to run as a Windows Service.

**Comment by sangjiexun** [comment]
Thank you for your patience answer 😀
